export {
  assembleSystemContext,
  createDefaultPromptSourceRegistry,
  createPromptSourceRegistry,
  createAttachmentPromptSource,
  createAutomationIntentPromptSource,
  createBrainstormingPromptSource,
  createContinuityPromptSource,
  createContextExtensionPromptSource,
  createGoalPlanPromptSource,
  createModePromptSource,
  createProjectInstructionsPromptSource,
  createProviderPromptSource,
  createRuntimeReminderPromptSource,
  renderBrainstormingPrompt,
  renderRuntimeContext,
  renderSystemContext,
  renderStableSystemContext,
  renderSystemCorePrompt,
} from '@peer-agent/system-context';
