export type ClientApi = NonNullable<Window['peerAgent']>;

function desktopOnly(method: string): never {
  throw new Error(`Peer Agent desktop preload is not available. ${method} must run inside Electron.`);
}

function unavailableMethod<T extends (...args: never[]) => unknown>(method: string): T {
  return ((..._args: Parameters<T>) => desktopOnly(method)) as unknown as T;
}

const unavailableApi: ClientApi = {
  getBootstrap: unavailableMethod('getBootstrap'),
  getClientSession: unavailableMethod('getClientSession'),
  listCapabilities: unavailableMethod('listCapabilities'),
  listProjects: unavailableMethod('listProjects'),
  getRuntimeProjection: unavailableMethod('getRuntimeProjection'),
  setLocale: unavailableMethod('setLocale'),
  approveLocalAction: unavailableMethod('approveLocalAction'),
  denyLocalAction: unavailableMethod('denyLocalAction'),
  executeClientToolCall: unavailableMethod('executeClientToolCall'),
  runHealthCheck: unavailableMethod('runHealthCheck'),
  listShellTasks: unavailableMethod('listShellTasks'),
  stopActiveShellTask: unavailableMethod('stopActiveShellTask'),
  stopShellTask: unavailableMethod('stopShellTask'),
  listShellPermissionRules: unavailableMethod('listShellPermissionRules'),
  addShellPermissionRule: unavailableMethod('addShellPermissionRule'),
  listSkills: unavailableMethod('listSkills'),
  refreshSkills: unavailableMethod('refreshSkills'),
  uploadSkill: unavailableMethod('uploadSkill'),
  enableSkill: unavailableMethod('enableSkill'),
  disableSkill: unavailableMethod('disableSkill'),
  mcpListInstalled: unavailableMethod('mcpListInstalled'),
  mcpListCapabilities: unavailableMethod('mcpListCapabilities'),
  mcpListCredentials: unavailableMethod('mcpListCredentials'),
  mcpPutCredential: unavailableMethod('mcpPutCredential'),
  mcpDeleteCredential: unavailableMethod('mcpDeleteCredential'),
  mcpInstall: unavailableMethod('mcpInstall'),
  mcpUpsertServer: unavailableMethod('mcpUpsertServer'),
  mcpUninstall: unavailableMethod('mcpUninstall'),
  mcpSetEnabled: unavailableMethod('mcpSetEnabled'),
  mcpSetToolVisibility: unavailableMethod('mcpSetToolVisibility'),
  mcpTestConnection: unavailableMethod('mcpTestConnection'),
  mcpRefreshManifest: unavailableMethod('mcpRefreshManifest'),
  mcpReadResource: unavailableMethod('mcpReadResource'),
  mcpGetPrompt: unavailableMethod('mcpGetPrompt'),
  mcpConnectAndRegister: unavailableMethod('mcpConnectAndRegister'),
  workspaceList: unavailableMethod('workspaceList'),
  workspaceEnsureDefault: unavailableMethod('workspaceEnsureDefault'),
  workspaceAdd: unavailableMethod('workspaceAdd'),
  workspaceSetActive: unavailableMethod('workspaceSetActive'),
  workspaceRemove: unavailableMethod('workspaceRemove'),
  workspaceInfo: unavailableMethod('workspaceInfo'),
  conversationsList: unavailableMethod('conversationsList'),
  conversationsCreate: unavailableMethod('conversationsCreate'),
  conversationsGet: unavailableMethod('conversationsGet'),
  conversationsUpdateTitle: unavailableMethod('conversationsUpdateTitle'),
  conversationsUpdateMode: unavailableMethod('conversationsUpdateMode'),
  conversationsAppendMessage: unavailableMethod('conversationsAppendMessage'),
  conversationsUpdateLastMessage: unavailableMethod('conversationsUpdateLastMessage'),
  conversationsReplaceMessages: unavailableMethod('conversationsReplaceMessages'),
  conversationsDelete: unavailableMethod('conversationsDelete'),
  conversationsAddUsage: unavailableMethod('conversationsAddUsage'),
  goalPlansList: unavailableMethod('goalPlansList'),
  goalPlansGet: unavailableMethod('goalPlansGet'),
  goalPlansCreate: unavailableMethod('goalPlansCreate'),
  goalPlansRevise: unavailableMethod('goalPlansRevise'),
  goalPlansApprove: unavailableMethod('goalPlansApprove'),
  goalPlansSetStatus: unavailableMethod('goalPlansSetStatus'),
  goalPlansRecordTaskEvidence: unavailableMethod('goalPlansRecordTaskEvidence'),
  goalPlansDelete: unavailableMethod('goalPlansDelete'),
  onGoalPlansChanged: unavailableMethod('onGoalPlansChanged'),
  chatSend: unavailableMethod('chatSend'),
  chatAbort: unavailableMethod('chatAbort'),
  chatStreamReattach: unavailableMethod('chatStreamReattach'),
  chatStreamListActive: unavailableMethod('chatStreamListActive'),
  restartHost: unavailableMethod('restartHost'),
  writePendingTask: unavailableMethod('writePendingTask'),
  consumePendingTask: unavailableMethod('consumePendingTask'),
  peekPendingTask: unavailableMethod('peekPendingTask'),
  clearPendingTask: unavailableMethod('clearPendingTask'),
  chatCompact: unavailableMethod('chatCompact'),
  promptSnapshotsList: unavailableMethod('promptSnapshotsList'),
  promptSnapshotsGet: unavailableMethod('promptSnapshotsGet'),
  promptContextEpochsList: unavailableMethod('promptContextEpochsList'),
  promptContextEpochEvents: unavailableMethod('promptContextEpochEvents'),
  promptContextEpochChain: unavailableMethod('promptContextEpochChain'),
  onChatStreamDelta: unavailableMethod('onChatStreamDelta'),
  onChatStreamThinking: unavailableMethod('onChatStreamThinking'),
  onChatStreamDone: unavailableMethod('onChatStreamDone'),
  onChatStreamAborted: unavailableMethod('onChatStreamAborted'),
  onChatStreamUsage: unavailableMethod('onChatStreamUsage'),
  onChatStreamToolCall: unavailableMethod('onChatStreamToolCall'),
  onChatStreamToolProgress: unavailableMethod('onChatStreamToolProgress'),
  onChatStreamToolResult: unavailableMethod('onChatStreamToolResult'),
  onChatStreamPermissionRequest: unavailableMethod('onChatStreamPermissionRequest'),
  onChatStreamError: unavailableMethod('onChatStreamError'),
  onChatStreamProviderRecovery: unavailableMethod('onChatStreamProviderRecovery'),
  onChatStreamConnectionRecovery: unavailableMethod('onChatStreamConnectionRecovery'),
  onChatCompaction: unavailableMethod('onChatCompaction'),
  onChatActiveStreamsChanged: unavailableMethod('onChatActiveStreamsChanged'),
  onWindowFullscreenChanged: unavailableMethod('onWindowFullscreenChanged'),
  llmListProviders: unavailableMethod('llmListProviders'),
  llmAddProvider: unavailableMethod('llmAddProvider'),
  llmUpdateProvider: unavailableMethod('llmUpdateProvider'),
  llmRemoveProvider: unavailableMethod('llmRemoveProvider'),
  llmSetDefault: unavailableMethod('llmSetDefault'),
  llmTestConnection: unavailableMethod('llmTestConnection'),
  llmOAuthStart: unavailableMethod('llmOAuthStart'),
  llmOAuthCancel: unavailableMethod('llmOAuthCancel'),
  llmListModels: unavailableMethod('llmListModels'),
  initialSettings: {},
  getSettings: unavailableMethod('getSettings'),
  updateSettings: unavailableMethod('updateSettings'),
  exportConfig: unavailableMethod('exportConfig'),
  importConfig: unavailableMethod('importConfig'),
};

export const clientApi: ClientApi = window.peerAgent ?? unavailableApi;
