export type AutomationLocale = 'en' | 'zh';

export const automationCopy = {
  en: {
    operations: 'Agent operations', automations: 'Automation tasks', subtitle: 'Delegate recurring work. Each occurrence starts a fresh, governed run.',
    pauseAll: 'Pause all', resumeAll: 'Resume all', newAutomation: 'New automation task', total: 'Automation tasks', active: 'Active', running: 'Running', needsAttention: 'Needs attention',
    search: 'Search automation tasks', noMatches: 'No matching automation tasks', tryAnotherSearch: 'Try another search.', emptyTitle: 'Automate recurring work', emptyDetail: 'Create a schedule, choose a workspace and confirm exactly what Peer may do.', createAutomation: 'Create automation task', pausedBanner: 'All schedules are paused. Running tasks continue.',
    loading: 'Loading automations…', loadFailed: 'Could not load automations.', retry: 'Retry', back: 'Back', cancel: 'Cancel', save: 'Save changes', create: 'Create automation', saving: 'Saving…',
    newTitle: 'New automation', editTitle: 'Edit automation', reviewTitle: 'Review automation', details: 'Details', schedule: 'Schedule', workspaceAccess: 'Workspace & access', behavior: 'Behavior', review: 'Review',
    name: 'Name', namePlaceholder: 'e.g. Daily repository health check', instructions: 'Instructions', instructionsPlaceholder: 'Describe exactly what Peer should do.', workspace: 'Workspace', timezone: 'Timezone', timezoneBoundDetail: 'Automatically uses the system timezone for this schedule.', scheduleType: 'Schedule type',
    once: 'Once', hourly: 'Hourly', daily: 'Daily', weekdays: 'Weekdays', weekly: 'Weekly', monthly: 'Monthly', customCron: 'Custom cron', dateTime: 'Date and time', hour: 'Hour', minute: 'Minute', everyHours: 'Every N hours', dayOfMonth: 'Day of month', cron: 'Cron expression',
    observe: 'Observe', observeDetail: 'Read-only. Peer may inspect and report, but cannot write.', workInWorkspace: 'Work in workspace', workInWorkspaceDetail: 'Writes run in an isolated Git worktree with captured changes.',
    timeout: 'Timeout (minutes)', notifySuccess: 'Notify when a run succeeds', notifySuccessOnlyOnChange: 'Only when the result changes', notifySuccessOnlyOnChangeDetail: 'Suppress repeated successful results that match the previous run.', preview: 'Next three runs', noPreview: 'No upcoming occurrence could be calculated.',
    prompt: 'Prompt', access: 'Access', notifications: 'Notifications', notifyAttention: 'Needs attention and failures', enabled: 'Enabled', disabled: 'Disabled',
    overview: 'Overview', runs: 'Runs', runNow: 'Run now', edit: 'Edit', pause: 'Pause', resume: 'Resume', nextRun: 'Next run', lastRun: 'Last run', created: 'Created', updated: 'Updated', consecutiveFailures: 'Consecutive failures',
    noRuns: 'No runs yet.', openReceipt: 'Open receipt', retryRun: 'Retry', cancelRun: 'Cancel', resultReceipt: 'Result receipt', conversation: 'Conversation', openConversation: 'Open conversation', status: 'Status', started: 'Started', finished: 'Finished', duration: 'Duration', notAvailable: 'Not available',
    summary: 'Summary', noSummary: 'No summary recorded.', comparison: 'Compared with previous run', previousResult: 'Previous result', resultChanged: 'Changed', resultUnchanged: 'No change', changes: 'Changes', noChanges: 'No file changes recorded.', verification: 'Verification', noVerification: 'No verification records.', evidence: 'Evidence', noEvidence: 'No evidence references.',
    branch: 'Branch', baseline: 'Baseline', additions: 'additions', deletions: 'deletions', filesChanged: 'files changed', error: 'Error', unknownError: 'Something went wrong.',
    activeState: 'Active', pausedState: 'Paused', notificationOn: 'Success notifications on', notificationOff: 'Success notifications off', timeoutMinutes: (value: number) => `${value} min timeout`,
    backToEdit: 'Back to edit', finalConfirmation: 'Final confirmation', confirmPolicy: 'Confirm the schedule, workspace, access and notification policy.', recovery: 'Recovery', runLatest: 'Run latest', overlap: 'Overlap', skip: 'Skip', runLatestSkipOverlap: 'Run latest · Skip overlap', attentionFailures: 'Attention and failures', attentionFailuresSuccesses: 'Attention, failures and successes', nextRuns: 'Next runs', safetyNote: 'Each run starts a fresh conversation. High-risk actions, deployment, merge and workspace-external writes remain blocked.', confirmChanges: 'Confirm changes', confirmEnable: 'Confirm & enable', createAndEnable: 'Create & enable', detectModel: 'Detection model', detectModelPlaceholder: 'Select a model', detecting: 'Detecting with model…', detectWithModel: 'Detect with model', detectFailed: 'Model detection failed. Local fallback was used.', detectNeedModel: 'Select a model for detection first.', confirmCreateTitle: 'Confirm automation', confirmCreateDetail: 'Review the detected name and schedule, then enable it.', confirmAndEnable: 'Confirm & enable', accessLabel: 'Access', scheduleLabel: 'Schedule', advancedSettings: 'Advanced settings', promptFirstDetail: 'Describe the recurring work. Name and schedule are generated after the first detection.', promptFirstPlaceholder: 'e.g. Every weekday at 9:00 check repository health and summarize failures', detectFromPrompt: 'Detect name & schedule', generatedPlan: 'Generated plan', generatedPlanDetail: 'Review or adjust what was detected. Workspace and timezone stay bound automatically.', editDefinition: 'Edit definition', newDelegation: 'New delegation', editorSubtitle: 'Describe the recurring work. Name and schedule are generated after detection.', promptTemplate: `Every weekday morning:
- Check repository health
- Summarize failed checks
- Note anything that needs attention`, createHomeTitle: 'New automation task', createHomeLede: 'Describe the recurring work in natural language. We will detect the name and schedule for you.', createHomeHint: 'Edit the template, then continue to detect and confirm.', chatDraftTemplate: `Let's set up a scheduled task together. First, explain how scheduled tasks work. Then ask me what I need to schedule and when it should run.`,  task: 'Task', workspacePath: 'Workspace path', workspaceBoundDetail: 'Bound to this workspace. Change the active workspace before creating a different automation.', workspaceRequired: 'Select a workspace before creating an automation.', frequency: 'Frequency', limitsNotifications: 'Limits & notifications', sectionWhat: 'What', sectionWhatDetail: 'Name the automation and describe the recurring work Peer should do.', sectionWhen: 'When', sectionWhenDetail: 'Choose how often it runs. Timezone follows this device.', sectionGuardrails: 'Guardrails', sectionGuardrailsDetail: 'Confirm where it runs, what it may change, and how it should notify you.', notifyOnSuccess: 'Notify on success', notifyOnSuccessDetail: 'Send a notification when a run succeeds.', fiveFieldCron: 'Five-field cron', reviewAction: 'Review', continueAction: 'Continue', backStep: 'Back', stepProgress: 'Creation steps',
    rule: 'Rule', missedRuns: 'Missed runs', preset: 'Preset', execution: 'Execution', currentWorkspace: 'Current workspace', isolatedWorktree: 'Isolated Git worktree', notifyAttentionFailures: 'Attention and failures', health: 'Health', failures: 'Failures', runNowOrWait: 'Run now or wait for the next scheduled occurrence.', triggered: 'Triggered', result: 'Result', seconds: (value: number) => `${value}s`,
    immutableReceipt: 'Immutable result receipt', run: 'Run', runAgain: 'Run again', openToContinue: 'Open the conversation to continue.', runFacts: 'Run facts', trigger: 'Trigger', scheduled: 'Scheduled', definitionVersion: 'Definition version', usage: 'Usage', inputTokens: 'Input tokens', outputTokens: 'Output tokens', cost: 'Cost', worktree: 'Worktree', files: 'Files', diff: 'Diff', retention: 'Retention', noFilesChanged: 'No files changed', retainedReview: 'Retained for review', cleanedUp: 'Cleaned up', noWorkspaceChanges: 'No workspace changes.',
  },
  zh: {
    operations: '智能体操作', automations: '自动化任务', subtitle: '委派重复性工作。每次触发都会启动一次全新、受治理的运行。',
    pauseAll: '全部暂停', resumeAll: '全部恢复', newAutomation: '新建自动化任务', total: '自动化任务', active: '已启用', running: '运行中', needsAttention: '需要处理',
    search: '搜索自动化任务', noMatches: '没有匹配的自动化任务', tryAnotherSearch: '请尝试其他搜索词。', emptyTitle: '自动执行重复工作', emptyDetail: '创建计划、选择工作区，并明确确认 Peer 可以执行的操作。', createAutomation: '创建自动化任务', pausedBanner: '所有计划均已暂停，正在运行的任务会继续。',
    loading: '正在加载自动化…', loadFailed: '无法加载自动化。', retry: '重试', back: '返回', cancel: '取消', save: '保存更改', create: '创建自动化', saving: '正在保存…',
    newTitle: '新建自动化', editTitle: '编辑自动化', reviewTitle: '确认自动化', details: '基本信息', schedule: '运行计划', workspaceAccess: '工作区与权限', behavior: '运行行为', review: '确认',
    name: '名称', namePlaceholder: '例如：每日仓库健康检查', instructions: '任务说明', instructionsPlaceholder: '准确描述 Peer 应该执行的工作。', workspace: '工作区', timezone: '时区', timezoneBoundDetail: '此计划自动使用系统时区。', scheduleType: '计划类型',
    once: '单次', hourly: '每小时', daily: '每天', weekdays: '工作日', weekly: '每周', monthly: '每月', customCron: '自定义 Cron', dateTime: '日期和时间', hour: '小时', minute: '分钟', everyHours: '每隔几小时', dayOfMonth: '每月第几天', cron: 'Cron 表达式',
    observe: '仅观察', observeDetail: '只读。Peer 可以检查并汇报，但不能写入。', workInWorkspace: '在工作区中工作', workInWorkspaceDetail: '写入任务会在隔离的 Git Worktree 中运行并记录变更。',
    timeout: '超时（分钟）', notifySuccess: '运行成功时通知', notifySuccessOnlyOnChange: '仅结果变化时通知', notifySuccessOnlyOnChangeDetail: '与上一次结果相同时不重复发送成功通知。', preview: '接下来三次运行', noPreview: '无法计算下一次运行时间。',
    prompt: '任务提示', access: '权限', notifications: '通知', notifyAttention: '需要处理和失败时通知', enabled: '已开启', disabled: '已关闭',
    overview: '概览', runs: '运行记录', runNow: '立即运行', edit: '编辑', pause: '暂停', resume: '恢复', nextRun: '下次运行', lastRun: '上次运行', created: '创建时间', updated: '更新时间', consecutiveFailures: '连续失败',
    noRuns: '暂无运行记录。', openReceipt: '查看收据', retryRun: '重试', cancelRun: '取消', resultReceipt: '结果收据', conversation: '会话', openConversation: '打开会话', status: '状态', started: '开始时间', finished: '结束时间', duration: '耗时', notAvailable: '暂无',
    summary: '摘要', noSummary: '没有记录摘要。', comparison: '与上次结果对比', previousResult: '上次结果', resultChanged: '有变化', resultUnchanged: '无变化', changes: '变更', noChanges: '没有记录文件变更。', verification: '验证', noVerification: '没有验证记录。', evidence: '证据', noEvidence: '没有证据引用。',
    branch: '分支', baseline: '基线', additions: '新增', deletions: '删除', filesChanged: '个文件变更', error: '错误', unknownError: '发生了错误。',
    activeState: '已启用', pausedState: '已暂停', notificationOn: '成功通知已开启', notificationOff: '成功通知已关闭', timeoutMinutes: (value: number) => `超时 ${value} 分钟`,
    backToEdit: '返回编辑', finalConfirmation: '最终确认', confirmPolicy: '请确认运行计划、工作区、权限和通知策略。', recovery: '错过计划', runLatest: '运行最近一次', overlap: '重叠运行', skip: '跳过', runLatestSkipOverlap: '运行最近一次 · 跳过重叠', attentionFailures: '需要处理和失败时通知', attentionFailuresSuccesses: '需要处理、失败和成功时通知', nextRuns: '接下来运行', safetyNote: '每次运行都会启动新会话。高风险操作、部署、合并以及工作区外写入仍会被阻止。', confirmChanges: '确认更改', confirmEnable: '确认并启用', createAndEnable: '创建并启用', detectModel: '检测模型', detectModelPlaceholder: '选择模型', detecting: '正在用模型检测…', detectWithModel: '用模型检测', detectFailed: '大模型检测失败，已使用本地回退结果。', detectNeedModel: '请先选择用于检测的模型。', confirmCreateTitle: '确认创建自动化', confirmCreateDetail: '请确认检测出的名称与计划，然后再启用。', confirmAndEnable: '确认并启用', accessLabel: '权限', scheduleLabel: '计划', advancedSettings: '高级设置', promptFirstDetail: '描述要重复执行的工作。名称与时间计划会在首次检测后自动生成。', promptFirstPlaceholder: '例如：每个工作日 9:00 检查仓库健康并汇总失败项', detectFromPrompt: '检测名称与计划', generatedPlan: '生成的计划', generatedPlanDetail: '可检查或调整检测结果。工作区与时区仍自动绑定。', editDefinition: '编辑定义', newDelegation: '新建委派', editorSubtitle: '描述要重复执行的工作，名称与计划会自动生成。', promptTemplate: `每个工作日早上：
- 检查仓库健康状态
- 汇总失败项
- 标出需要处理的事项`, createHomeTitle: '新建自动化任务', createHomeLede: '用自然语言描述要重复执行的工作，名称与计划会自动检测生成。', createHomeHint: '可直接改写模板，然后继续检测并确认。', chatDraftTemplate: `我们一起来设置一个已安排任务吧。首先，说明已安排任务在 ChatGPT 中的工作方式。然后询问我需要安排什么，以及应该在什么时候运行。`,  task: '任务', workspacePath: '工作区路径', workspaceBoundDetail: '已绑定此工作区。如需在其他工作区创建，请先切换当前工作区。', workspaceRequired: '请先选择工作区，再创建自动化。', frequency: '频率', limitsNotifications: '限制与通知', sectionWhat: '做什么', sectionWhatDetail: '命名自动化，并描述 Peer 应重复执行的工作。', sectionWhen: '何时执行', sectionWhenDetail: '选择运行频率。时区跟随当前设备。', sectionGuardrails: '边界', sectionGuardrailsDetail: '确认运行位置、可写范围，以及成功时是否通知。', notifyOnSuccess: '成功时通知', notifyOnSuccessDetail: '运行成功后发送通知。', fiveFieldCron: '五段 Cron', reviewAction: '确认', continueAction: '继续', backStep: '上一步', stepProgress: '创建步骤',
    rule: '规则', missedRuns: '错过运行', preset: '预设', execution: '执行环境', currentWorkspace: '当前工作区', isolatedWorktree: '隔离的 Git Worktree', notifyAttentionFailures: '需要处理和失败时通知', health: '运行状况', failures: '失败次数', runNowOrWait: '立即运行，或等待下一次计划触发。', triggered: '触发方式', result: '结果', seconds: (value: number) => `${value} 秒`,
    immutableReceipt: '不可变结果收据', run: '运行', runAgain: '再次运行', openToContinue: '打开会话以继续处理。', runFacts: '运行事实', trigger: '触发来源', scheduled: '计划时间', definitionVersion: '定义版本', usage: '用量', inputTokens: '输入 Token', outputTokens: '输出 Token', cost: '费用', worktree: 'Worktree', files: '文件', diff: '差异', retention: '保留状态', noFilesChanged: '没有文件变更', retainedReview: '已保留供审查', cleanedUp: '已清理', noWorkspaceChanges: '没有工作区变更。',
  },
} as const;

export type AutomationCopy = typeof automationCopy.en | typeof automationCopy.zh;

export function getAutomationCopy(isZh: boolean): AutomationCopy {
  return isZh ? automationCopy.zh : automationCopy.en;
}
